name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for DapperDemo
      run: dotnet restore DapperDemo/DapperDemo
    
    - name: Build DapperDemo
      run: dotnet build DapperDemo/DapperDemo --no-restore
